### ISSUE TITLE
About intermediate training on RACE

### ISSUE THREAD

**Issue by hbin0701** [nyu-mll/quality#4]
Dear Authors,
The paper indicates that the the authors performed intermediate training on Deberta with RACE + QuaLITY.
Then, I'm curious as to if any attempts to fine-tune the **DPR** on RACE has been made.

**Comment by yzpang** [comment]
Sorry for the delay. No, but I think what you proposed is a good idea! We were using off-the-shelf DPR retriever which is not optimized for retrieving sentences. A better retriever may further improve QA results on QuALITY. 
cc: @zphang @angie-chen55

**Comment by hbin0701** [comment]
Thank you :)
