### ISSUE TITLE
How to load FastTextScorer data?

### ISSUE THREAD

**Issue by yhshu** [nyu-mll/quality#8]
Hi there,
when I am trying to use FastTextScorer, I get this result:
```
Traceback (most recent call last):
  File "extract.py", line 6, in <module>
    scorer=extraction.FastTextScorer(),  # depending on the retrieval model: SimpleScorer(), FastTextScorer(), DPRScorer()
TypeError: __init__() missing 1 required positional argument: 'data'
```
So would you please provide me with some clues about what data to load?

**Comment by yzpang** [comment]
Hi yhshu, @zphang just revamped the lrqa code. Please see the updated lrqa folder for updated instruction and updated code.

Please see the updated README in the lrqa folder:

> 
> To use fastText, you will first need to download fastText embeddings from [here](https://dl.fbaipublicfiles.com/fasttext/vectors-english/crawl-300d-2M.vec.zip), and then run the following script:
> 
> ```bash
> python lrqa/scripts/save_fasttext_embeddings.py \
>     --fasttext_data_path /path/to/crawl-300d-2M.vec \
>     --output_path /path/to/fasttext_embeddings.p
> ```
